#!/bin/bash

echo "computing slice for LongestCommonSubsequenceTest"

mkdir -p slices/similarity_slices/LongestCommonSubsequenceTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:38:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:39:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:40:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:41:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:42:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:43:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:44:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:45:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:46:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:47:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:48:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:49:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequenceApply:50:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:70:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:71:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:72:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:73:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:74:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:75:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:76:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:77:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:79:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:81:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:82:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:83:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLongestCommonSubsequence:84:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:105:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:106:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:107:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:108:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:109:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:110:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:111:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:112:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:114:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:116:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:117:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:118:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceTest.testLogestCommonSubsequence:119:*>slices/similarity_slices/LongestCommonSubsequenceTest/LongestCommonSubsequenceTestLongestCommonSubsequenceTest39.txt

#Total Asserts in org.apache.commons.text.similarity/LongestCommonSubsequenceTest=============39
#Total Tests in org.apache.commons.text.similarity/LongestCommonSubsequenceTest=============0
