#!/bin/bash

echo "computing slice for LongestCommonSubsequenceDistanceTest"

mkdir -p slices/similarity_slices/LongestCommonSubsequenceDistanceTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:38:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:39:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:40:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:41:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:42:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:43:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:44:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:45:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:46:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:47:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:48:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:49:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/similarity_traces/LongestCommonSubsequenceDistanceTest.trace org.apache.commons.text.similarity.LongestCommonSubsequenceDistanceTest.testGettingLogestCommonSubsequenceDistacne:50:*>slices/similarity_slices/LongestCommonSubsequenceDistanceTest/LongestCommonSubsequenceDistanceTestLongestCommonSubsequenceDistanceTest13.txt

#Total Asserts in org.apache.commons.text.similarity/LongestCommonSubsequenceDistanceTest=============13
#Total Tests in org.apache.commons.text.similarity/LongestCommonSubsequenceDistanceTest=============0
