#!/bin/bash

echo "computing slice for FormattableUtilsTest"

mkdir -p slices/text_slices/FormattableUtilsTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testSimplestFormat:41:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:46:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:47:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:48:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:49:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:50:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:51:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:52:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:53:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:54:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testDefaultAppend:55:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:61:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:62:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:63:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:64:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:65:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:66:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:67:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:69:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:71:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharacter:73:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:79:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:80:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:81:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:82:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:83:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:84:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:85:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:87:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:89:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:91:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:94:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:95:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:96:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:97:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:98:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:99:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:100:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:102:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:104:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testEllipsis:106:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:117:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:118:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:119:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:120:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:121:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:122:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:123:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:125:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:127:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:129:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:132:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:133:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:134:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest54.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:135:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest55.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:137:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest56.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:138:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest57.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:139:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest58.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:141:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest59.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:143:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest60.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/FormattableUtilsTest.trace org.apache.commons.text.FormattableUtilsTest.testAlternatePadCharAndEllipsis:145:*>slices/text_slices/FormattableUtilsTest/FormattableUtilsTestFormattableUtilsTest61.txt

#Total Asserts in org.apache.commons.text/FormattableUtilsTest=============61
#Total Tests in org.apache.commons.text/FormattableUtilsTest=============0
