#!/bin/bash

echo "computing slice for AlphabetConverterTest"

mkdir -p slices/text_slices/AlphabetConverterTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.javadocExampleTest:110:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.javadocExampleTest:111:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.javadocExampleTest:112:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.javadocExampleTest:113:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.javadocExampleTest:114:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.unicodeTest:147:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.unicodeTest:154:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.test:204:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.test:205:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.test:206:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.test:207:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.test:208:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.test:217:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.test:225:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.test:228:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testCreateConverterFromCharsOne:250:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testCreateConverterFromMapAndEquals:260:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testCreateConverterFromMapAndEquals:261:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testEquals:275:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testEquals:276:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testEqualsWithSameObject:288:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testEqualsWithNull:297:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testCreateConverterFromCharsAndEquals:310:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/AlphabetConverterTest.trace org.apache.commons.text.AlphabetConverterTest.testDecodeReturningNull:319:*>slices/text_slices/AlphabetConverterTest/AlphabetConverterTestAlphabetConverterTest24.txt

#Total Asserts in org.apache.commons.text/AlphabetConverterTest=============24
#Total Tests in org.apache.commons.text/AlphabetConverterTest=============0
