#!/bin/bash

echo "computing slice for ExtendedMessageFormatTest"

mkdir -p slices/text_slices/ExtendedMessageFormatTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testExtendedFormats:60:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testExtendedFormats:61:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testExtendedFormats:62:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testExtendedFormats:63:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testExtendedFormats:64:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testExtendedFormats:65:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEscapedQuote_LANG_477:75:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEmbeddedPatternInChoice:85:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEscapedBraces_LANG_948:96:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEscapedBraces_LANG_948:101:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testChoiceQuoteJustBeforeBraceEnd_TEXT_106:112:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testChoiceQuoteJustBeforeBraceEnd_TEXT_106:113:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testExtendedAndBuiltInFormats:155:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testExtendedAndBuiltInFormats:156:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testOverriddenBuiltinFormat:281:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testOverriddenBuiltinFormat:282:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:316:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:317:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:319:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:323:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:324:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:328:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:329:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:333:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:334:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:338:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:339:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:343:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testEqualsHashcode:344:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.checkBuiltInFormat:396:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.checkBuiltInFormat:397:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testCreatesExtendedMessageFormatTakingString:472:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar slicer.jar -m=1 -p trace/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.text.ExtendedMessageFormatTest.testCreatesExtendedMessageFormatTakingString:473:*>slices/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest33.txt

#Total Asserts in org.apache.commons.text/ExtendedMessageFormatTest=============33
#Total Tests in org.apache.commons.text/ExtendedMessageFormatTest=============0
